spring:
  application:
    name: "test-DiscoveryClient"

server:
  port: 8081
  tomcat:
    basedir: "/data/apps/temp" #避免系统长时间空闲后报错

#eureka:
#  instance:
##    ipAddress: http://127.0.0.1:8080
#    instance-id: ${spring.cloud.client.hostname}:${spring.application.name}:${server.port}
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/
#    #1.6. Eureka’s Health Checks
#    #healthcheck:
#    #  enabled: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
service-url:
  user-service: http://ribbon-service