spring:
  application:
    name: "gateway"
  profiles:
    #discovery 基于自动发现的方式
    #static 基于静态配置路由的方式
    active: discovery

server:
  port: 9999

eureka:
  client:
#    register-with-eureka: true
#    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8761/eureka/

# enable actuator & use url: http://127.0.0.1:9999/actuator/gateway/routes
#management:
#  endpoint:
#    gateway:
#      enabled: true # default value
#  endpoints:
#    web:
#      exposure:
#        include: gateway

logging:
  level:
    org.springframework.cloud.gateway: debug

---
#基于自动发现的配置方式
spring:
  profiles: discovery
  cloud:
    gateway:
      discovery:
        locator:
          #enable=true后可通过 http://127.0.0.1:9999/ribbon-service/api/test/checkLogin 访问
          #所有注册的服务都可以通过ServiceId前缀进行匹配访问
          enabled: true
          lowerCaseServiceId: true

---
spring:
  profiles: static
  cloud:
    gateway:
      routes:
      - id: t
        uri: lb://RIBBON-SERVICE
        predicates:
          - Path=/t/**
        filters:
          - StripPrefix=1
      - id: test
        uri: http://127.0.0.1:8080/
        predicates:
          - Path=/test/**
        filters:
        #剥离path前{2}个
        # 例如用/test/aaa/get/config请求 实际路由时候回用 /get/config请求
          - StripPrefix=2
        # 匹配指定路径的路由
      - id: path_route
        uri: https://h5.baike.qq.com/
        predicates:
        - Method=GET,POST
        filters:
        - StripPrefix=1
      - id: setstatusint_route
        uri: https://example.org
        predicates:
        - Path=/444/**
        filters:
        - SetStatus=401

