
spring:
  datasource:
    url: jdbc:mysql://localhost/cas?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 20
      hikari.max-lifetime: 30000
      hikari.idle-timeout: 30000
      data-source-properties:
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        cachePrepStmts: true
        useServerPrepStmts: true

mybatis:
  mapper-locations: classpath*:mapper/**/*.xml
  type-aliases-package: org.fran.springcloud.dao.mapper;com.cgtn.multiLanguage.live.dao.mapper