#feign:
#  client:
#    config:
#      feignName: myServiceName
#      connectTimeout: 5000
#      readTimeout: 5000
#      loggerLevel: full
#      encoder: com.example.MyEncoder
#      decoder: com.example.MyDecoder
#      contract: com.example.MyContract